config/routes.rb
Rails.application.routes.draw do
  root 'games#index'
  resource:games do
    collection do
      get "blockbreaking"
      get "runningame"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == Rails.application.credentials[:basic_auth][:user] && password == Rails.application.credentials[:basic_auth][:pass]
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

  def blockbreaking
  end

  def runninggame
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_gameselection.html.erb
<div class="swiper-container slider1">
	<div class="swiper-wrapper">

		<div class="swiper-slide" onmouseover="mouseover1();" onmouseout="mouseout1();"/>
			<%= link_to image_tag('blockbreaking.png', class:"aclass",id:"blockbreaking"),blockbreaking_games_path%> </div>
		<div class="swiper-slide" onmouseover="mouseover2();" onmouseout="mouseout2();"/>
			<%= link_to image_tag('runninggame.png', class:"aclass",id:"runningman"),runningame_games_path%> </div>
		<div class="swiper-slide" onmouseover="mouseover3();" onmouseout="mouseout3();"/>
			<%= link_to image_tag('batu.png', class:"aclass"),root_path%> </div>

	</div>
	  <div class="swiper-button-prev"></div>
	<div class="swiper-button-next"></div>
</div>

	<div class="swiper-pagination"></div>
</div>

<script>
	window.addEventListener('DOMContentLoaded', function() {
	var slider1 = new Swiper ('.slider1', {
		loop: true,
		initialSlide: -1,
		spaceBetween: 20,
		slidesPerView: 3,
		speed: 500,
		navigation: {
			nextEl: '.swiper-button-next',
			prevEl: '.swiper-button-prev'
    },
    pagination: {
      el: '.swiper-pagination',
      type: 'bullets',
      clickable: true,
    },
	});
	}, false);
</script>

app/views/games/blockbreaking.html.erb
  <body class=block-body>
    <div class="block-gamen">
      <canvas id="block-myCanvas" width="720" height="480"></canvas>
    </div>
    <div class="block-sitagamen">
      <div class="block-modoru">
        <%= link_to "TOPへ",root_path, {class:"block-modorubtn"} %>  
        <%= link_to "リセット",blockbreaking_games_path, {class:"block-modorubtn"} %>
      </div>
    </div>
    <div class="block-textbox">
      <div class="block-textbox-explanation">
      <p>
        操作方法：<br>
        &nbsp;&nbsp;キーボードの ◀︎ ▶︎ ボタンにてパドルを移動させブロックを壊してください。<br>
        &nbsp;&nbsp;▼ ボタンにてボールを止める事が出来ます。
      </p>
      <div>
    </div>
  </body>

  <script>
    $(function(){
      var canvas = document.getElementById("block-myCanvas");
      // キャンバスを取得するためのコード。事前準備。
      var ctx = canvas.getContext("2d");
      // キャンバスの2D描画コンテキストは実際にCanvasに描画するために使用。2Dを宣言する。線や四角や塗り潰し等が出来る。事前準備。
      var x = canvas.width / 2;
      // 枠の横幅を定義する。ボールの初期位置。
      var y = canvas.height - 30;
      // 枠の縦幅を定義する。ボールの初期位置。

      var dx = 6;
      var dy = -6;
      // 微小な変化を表現。アニメーション用。// ⭐️玉の移動スピード。

      var ballRadius = 10;
      // ⭐️ボールの半径。

      var paddleHeight = 10;
      var paddleWidth = 225;
      var paddleX = (canvas.width - paddleWidth)/2;
      // ⭐️ボールがぶつかるパドルの定義。

      var rightPressed = false;
      var leftPressed = false;
      var upPressed = false;
      var downPressed = false;
      // パドルの右、左、上、下ボタンを定義。最初は制御ボタンは押されていないため、どちらにおいてもデフォルトの値はfalseとする。
      var score = 0;
      var lives = 1;
      // プレイヤーにスコア、ライスを定義。
      var brickRowCount = 2;
      var brickColumnCount = 6;
      var brickWidth = 100;
      var brickHeight = 25;
      var brickPadding = 10;
      var brickOffsetTop = 30;
      var brickOffsetLeft = 30;
      // ⭐️ブロック間の情報を整理。

      var bricks = [];
      // bricksの配列を宣言する。破壊するブロック。
      // ブロックのための、2次元配列を操作する入れ子を使った数列のコードを書き上げること。
      // しかし、その前に幅と高さ、行と配列などといった情報を定義するいくつかの変数が必要となる、
      for(var c = 0; c < brickColumnCount; c++) {
      // ブリックス関数を宣言したが、それが二重配列になっていなかったため、二重配列を定義する。
      // ⭐️一つの二次元配列で全てのブロックを記載する。
        bricks[c] = [];
        // brick[c]も配列の中に入っている。
        for(var r = 0; r < brickRowCount; r++) {
        // その中を連想配列が入っている。
        bricks[c][r] = {x: 0, y: 0, status:1};
        // 衝突フラグを立てるためにstatusを定義している。
        }
      }

    function collisionDetection(){
      // ブロックの衝突関数を定義する。
      for(var c = 0; c < brickColumnCount; c++) {
      // ブリックス関数を宣言したが、それが二重配列になっていなかった。
      // ⭐️一つの二次元配列で全てのブロックを記載する。ブロックで壊す箱と定義文は似ている。
        for(var r = 0; r < brickRowCount; r++) {
          var b = bricks[c][r];
          if(b.status == 1) {
            // 衝突した時statusを0にする。
            if(x > b.x && x < b.x + brickWidth && y > b.y && y < b.y + brickHeight) {
            // もしボールの中央がブロックの1つの座標の内部だったらボールの向きを変更する。
              dx = dx / Math.abs(dx) * (Math.floor(Math.random() * 15 )+3);
              dy = -(dy / Math.abs(dy) * (Math.floor(Math.random() * 15 )+3));
              // ⭐️y方向を反転させる。
              b.status = 0;
              score++;
              // ぶつかるとscoreを1加算する。今回はスコアをつけてない。
              if(score == brickRowCount * brickColumnCount) {
                // ⭐️スコアーがブロックの縦※横と同じ数になった時、以下の処理を行う。
                alert("ゲームクリア！");
                document.location.reload();
              }
            }
          }
        }
      }
    }

    function drawScore() {
    // スコアを描写。
      ctx.font = "16px Arial";
      ctx.fillStyle = "#0095DD";
      ctx.fillText("Score:" + score, 8, 20);
    }

    function drawLives() {
    // ライフを描写。
      ctx.font = "16px Arial";
      ctx.fillStyle = "#0095DD";
      ctx.fillText("Score:" + lives, canvas.width - 65, 20);
    }

    function drawBall(){
    // ボールを描画。
      ctx.beginPath();
      ctx.arc(x, y, ballRadius, 0, Math.PI * 2);
      // ちょうど中央にくるように位置を調整する。円。
      // arc(x, y, ボールの半径, 0, Math.PI * 2)
      ctx.fillStyle = "white";
      ctx.fill();
      // 塗り潰しの実行。
      ctx.closePath();
      // パスを閉じる。
    }

    function drawPaddle(){
    // ⭐️ボールを弾くパドルを関数を作成。
      ctx.beginPath();
      // パスを開く。事前準備。
      ctx.rect(paddleX, canvas.height - paddleHeight, paddleWidth, paddleHeight);
      // ⭐️(paddleX, パドルの高さ位置, パドルの幅, パドルの高さ)描写される。弾かれるものとは別。大きさを決める。
      ctx.fillStyle = "red";
      ctx.fill();
      // 塗り潰しの実行。
      ctx.closePath();
      // パスを閉じる。
    }

  function drawBricks() {
  // ⭐ブロック描画搬送？を定義する。
    for(var c = 0; c < brickColumnCount; c++){
    // 二重forにて対応する？列に対しての定義文?ブロックの横関係。
      for(var r = 0; r < brickRowCount; r++){
      // ブロックの縦幅関係。
        if(bricks[c][r].status == 1) {
          // sutatusが1の時はまだ衝突フラグがある時ということのなので
          var brickX = (c * (brickWidth + brickPadding)) + brickOffsetLeft;
          var brickY = (r * (brickHeight + brickPadding)) + brickOffsetTop;
          // ⭐️それぞれの大きさ、列と幅を考慮して計算する。
          bricks[c][r].x = brickX;
          bricks[c][r].y = brickY;
          // ⭐️ブロック形を表現している。枠のようなもの？絵で書かれているものとは違う。0にするとブロックは弾かれない。
          ctx.beginPath();
          // パスを開く。
          ctx.rect(brickX, brickY, brickWidth, brickHeight);
          // ⭐️ブロックを描画する部分を記載する。全て上の方で定義しているものを流用している。
          ctx.fillStyle = "red";
          ctx.fill();
          // 塗り潰しの実行。
          ctx.closePath();
          // パスを閉じる。
        }   
      }
    }
  }

  function draw() {
  // 連続したデータを表現。
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    // ⭐️Canvasの内容を削除するメゾット、clearRect().
    // clearRect(0, 0, 横幅, 縦幅)。一回消した後に新しいボールを再度描画しているため動いているように見える。
    drawBall();
    drawBricks();
    drawPaddle();
    // 関数の呼び出し。ボール、ブロック、パドルを表示。
    // drawScore();
    // drawLives();
    // スコアを描画する。ライフを表示する。
    collisionDetection();
    // ブロックの衝突勘案を表示する。


    if(x + dx < 0 + ballRadius){
      // 画面の左側を反転させる。ボールの跳ね返りを表す。
      // もし、ボールの位置のxの値が0未満だったら、符号反転させた値を設定することで、x軸方向の動きの向きを変える。
      dx = -dx;
    }
    if(x + dx > canvas.width - ballRadius){
      // 画面の右側を反転させるせる。xの値がcanvasより、大きくなった時、xの値を反転する。
      dx = -dx;
    }
    if(y + dy < 0 + ballRadius){
      // 上の壁を定義する。
      // もし、ボールの位置のyの値が0未満だったら、符号反転させた値を設定することで、y軸方向の動きの向きを変える。
      // ballRadius、半径を足したり引くことによって、これを行わないとボールが弾かれたからめり込む。
      dy = -dy;
    }
    else if(y + dy > canvas.height - ballRadius){
      // 下の壁を設定する。
      // yの値がcanvasより、大きくなった時、yの値を反転する。

      if(x > paddleX && x < paddleX + paddleWidth) {
      // ボールの位置がパドルのx座標範囲内だった場合。
        if(y = y - paddleHeight) {
          dx = dx / Math.abs(dx) * (Math.floor(Math.random() * 15 )+3);
          dy = -(dy / Math.abs(dy) * (Math.floor(Math.random() * 15 )+3));
          // 板がランダムにボールを弾く。
        }
      }
      else {
        lives --;
        if(!lives) {
          // 失敗するたびにライフが引かれる。 ライフがなっかった時。現在未使用。
          document.location.reload();
        }
        else {
          x = canvas.width / 2;
          y = canvas.height - 30;
          dx = 3;
          dy = -3;
          paddleX = (canvas.width - paddleWidth) / 2;
        }
      }
    }
    
    if (rightPressed && paddleX < canvas.width - paddleWidth) {
      // 右矢印を押している時 & 右側の端までパドルが行っていない時。
      paddleX = paddleX + 20;
      // 右側のキーを押されていた、パドルの座標を。
    }
    else if (leftPressed && paddleX > 0) {
      // 左矢印を押している時 & 左側の端までパドルが行っていない時。
      paddleX = paddleX - 20;
      // 左側のキーを押されていた、パドルの座標を。
    }
    x = x + dx;
    y = y + dy;
    // xとyに毎フレーム描画した後に小さな値を加え、ボールが動いているように見せる。
    requestAnimationFrame(draw);
    // 繰り返し処理用。
    // 固定の10秒のフレームレートではなくブラウザに制御を託している。
    // これは古いsetlnterval()メゾットよりも効率的で滑らかなアニメーションループを生み出す。
  }

  document.addEventListener("keydown", keyDownHandler,false);
  // ddEventListenerさまざまなイベント処理を実行することが出来るメゾット。
  // keydown、キーを押している時に反応。
  document.addEventListener("keyup", keyUpHandler,false);
  // keyup、キーを離した時に反応。
  // document.addEventListener("mousemove", mouseMoveHandler, false);
  // マウスで操作する。mouseMoveHandlerは自分で定義しているので名前はなんでもいい？

  
  function keyDownHandler(e) {
    // 関数の作成.キーを押している時。eは引き数。
    if(e.key == "Right" || e.key == "ArrowRight"){
      // 大抵のブラウザでは左右の矢印キーにそれぞれArrowLeftとArrowRightが対応している。
      // ただし、IE/Edgeに対応するために、LeftとRightも確認する必要がある。
      rightPressed = true;
      // rightPressedをtrueにする。
    }
    else if(e.key == "Left" || e.key == "ArrowLeft"){
      // 左を押した時。
      leftPressed = true;
    }
    else if(e.key == "ArrowUp"){
      // dx = dx / Math.abs(dx) * 10;
      // dy = dy / Math.abs(dy) * 10;
      // 加速機能。
    }
    else if(e.key == "ArrowDown"){
      dx = dx /10000;
      dy = dy /10000;
      // 減速機能。
    }
  }

  function keyUpHandler(e) {
    // 関数の作成.キーを話したと時。
    // eは引き数。
    if(e.key == "Right" || e.key == "ArrowRight"){
      // 大抵のブラウザでは左右の矢印キーにそれぞれArrowLeftとArrowRightが対応している。
      // ただし、IE/Edgeに対応するために、LeftとRightも確認する必要がある。
      // 右を押した時。
      rightPressed = false;
      // rightPressedをtrueにする。
    }
    else if(e.key == "Left" || e.key == "ArrowLeft"){
      // 左を押した時。
      leftPressed = false;
    }
    else if(e.key == "ArrowUp"){
      dx = dx / Math.abs(dx) * 6;
      dy = dy / Math.abs(dy) * 6;
      // 加速機能を元に戻す。
    }
    else if(e.key == "ArrowDown"){
      dx = dx / Math.abs(dx) * 6;
      dy = dy / Math.abs(dy) * 6; 
      // 減速機能を元に戻す。
    }
  }

  // function mouseMoveHandler(e) {
  // // この関数ではまずビューポイントの水平方向のマウスの位置(e.clientX)から
  // // キャンバスを左端とビューポートの左の距離(canvas.offsetLeft)を引いて
  // // relativeXの値を導出。これはキャンバスの左端とマウスカーソルの
  // // 距離をちょうど同じにする。
  //   var relativeX = e.clientX - canvas.offsetLeft;
  //   if(relativeX > 0 && relativeX < canvas.width) {
  //     paddleX = relativeX - paddleWidth / 3;
  //   // これでマウスで操作することが出来るようになる。数字はバーのスピード。
  //   }
  // }

    draw();
    // ⭐固定の10秒のフレームレートではなくブラウザに制御を託している。
    // ブラウザはルレームレートを適切に同期し図形を必要な時だけ描画する。
    // これは古いsetlnterval()メゾットよりも効率的で滑らかなアニメーションループを生み出す。

    // var interval = setInterval(draw, 10);
    // ゲームオーバーを実装する。インターバル変数を宣言する。

    // setInterval(draw,10)
    // Canbasの映像を毎フレーム、定期的に更新し続けるためには何度も実行される関数を定義する必要がある。
    // setInterval()といったJavaScriptのタイミング関数を用いれば同じ関数を何度も実行できる。
    // 無限に続くsetinterval()は10ミリ秒おきにずっと、あらいは自らが止めるまで続く。
    });
  </script>

app/views/games/index.html.erb
<div class="wrapper">
  <div class="master">

    <div class="master__main">

      <div class="master__main__header">
        <div class="master__main__header__top">
          <%= image_tag 'rogo1.png', class:"rogo"%>
        </div>
        <div class="master__main__header__under"></div>
      </div>

      <div class="master__main__center">    
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.3/css/swiper.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.3/js/swiper.min.js"></script> 
        <div class="master__main__center__name">
          <div class="master__main__center__name__frame" id="gamename" >
          </div>
        </div>
        <div class="master__main__center__game">
          <div class="master__main__center__game__image">
            <%=render "gameselection"%>
          </div>
        </div>
      </div>

      <div class="master__main__footer">
        <div class="master__main__footer__top">
        </div>
        <div class="master__main__footer__under">
        </div>          
      </div>

    </div>
  </div>
</div>

app/views/games/runningame.html.erb
  <body class=running-body>
    <div class="running-gamen">
      <canvas id="running-myCanvas" width="720" height="480"></canvas>
    </div>
    <div class=running-sitagamen>
      <div class="running-modoru">
        <%= link_to "TOPへ",root_path, {class:"running-modorubtn"} %>  
        <%= link_to "リセット",runningame_games_path, {class:"running-modorubtn"} %>
      </div>
    </div>
    <div class="running-textbox">
      <div class="running-textbox-explanation">
      <p>
        操作方法：<br>
        &nbsp;&nbsp;キーボードの ▲ ボタンにてゲーム開始します。<br>
        &nbsp;&nbsp;◀️ ▶️ ボタンにてキャラクターを回転させます。<br>
        &nbsp;&nbsp;一定以上傾いた状態で、キャラクターが地面にぶつかるとゲームオーバーとなります。
      </p>
      <div>
    </div>
  </body>


  <script>
    $(function(){
    var canvas = document.getElementById("running-myCanvas");
    // HTMLのタグをHTMLタグのキャンバスに反映する。画面の準備。
    var ctx = canvas.getContext("2d");
    // 変数にデータを代入するキャンバス描画するために必要な処理。二次元の画面。画面の準備。

    var perm = [];
    // 山道の凸凹を作る。山の描写。

    while (perm.length < 255) {
    // permの最大値が255。255になるまで繰り返す。山の描写。
      while (perm.includes(val = Math.floor(Math.random() * 255)));
      // Math.floor整数（小数点繰上げ）をとる。Math.random()0〜1の値をランダムに出力する。繰り返し。山の描写。
      perm.push(val);
      // 0〜255の整数が入っていたら処理が実行される。
      // whileの条件。配列にvalの値を入れる。山の描写。
    }
    var lerp = (a, b, t) => a + (b - a) * (1 - Math.cos(t * Math.PI)) / 2;
    // 関数を変数に入れている。線形分離。ベクトルa、bに分断し、tをかけることで？山の斜面を凸凹を表している。山の描写。
    // (1 - Math.cos(t * Math.PI))/ 2 線形分離の調整を行っている。これは 1 - cos(t * π)を行っている。πの整数倍となるので、cosは 1 か -1 となる。
    // 山の斜面を変更することが出来る。山の斜面。
    var noise = x => {
      // ノイズを言う関数を指定する。山の描写。
      x = x * 0.01 % 255;
      // 山が数を変更する。上記を解決するために255で割った余りを配列のindexに指定する.
      // 0.01倍することによってギザギザ（山の斜面）を拡大する。ズームアップ。山の描写。
      return lerp(perm[Math.floor(x)], perm[Math.ceil(x)], x - Math.floor(x));
      // ノイズ関数に線形分離の値を入れる。Math.floor整数（小数点繰上げ）。
      // 適当に決定しても良い。山の描写。
    }
    var player = new function() {
    // プレイヤーを定義する。関数の宣言。プレイヤーの定義。
      this.x = canvas.width / 2;
      // キャンバスの中央。
      this.y = 0;
      // 一番上。
      this.ySpeed = 0;
      // キャラクターが落ちてくるスピード。
      this.rot = 0;
      // 回転角度。
      this.rSpeed = 0;
      // 回転スピードを設定する。プレーヤーの角度。
      this.img = new Image();
      // イメージ変数の作成。
      this.img.src = "/images/chara.png";
      // image_tag asset_path("MHW.jpg", alt: "ゲーム画像1")
      // イメージの読み込み。画像ファイルから。
      this.draw = function() {
        // draw描画するための関数。
        var p1 = canvas.height - noise(t + this.x) * 0.4;
        // 山の高さの調整。
        // キャラクターを山の斜面を走らせる。山に使用したノイズを流用することによって山の上を走っているように見せれる。
        // noise(t + this.x)this.xを足している。プレイヤーの高さを反映している。
        var p2 = canvas.height - noise(t + 5 + this.x) * 0.4;
        var grounded = 0
        // 地面設置のグラフを設置。プレイヤーの角度を編集する。
        if(p1 - 25 > this.y) {
        // p1は山の斜面の境界の位置を示している。キャラクターのy座標が山の斜面に一致するかどうか条件分岐している。
          this.ySpeed = this.ySpeed + 0.1;
          // 落ちてくるスピード。
        } else {
          // 山の斜面に当たると反応する。
          this.ySpeed = this.ySpeed - (this.y - (p1 - 23.5));
          // 振動を与える。バウンドするようになる。
          // 0地点に当たって時におこる処理。
          this.y = p1 - 23.5;
          // キャラクターにバウンドを与える。
          // 山の斜面に触れると、this.yとp1が固定される。山ジグザグ式なので、これがないとどんどん落ちいく。
          // 山の斜面に当たるとySpeedが0になる。これ以上落ちなくなる。 
          grounded = 1;
          // 地面にふれると1を代入させる。
        }
        this.y = this.y + this.ySpeed;
        // ｙスピードの分だけ速度を上げて（下げて）いく。キャラクターが降下するようになる。
        if(!playing || grounded && Math.abs(this.rot) > Math.PI * 0.5) {
        // x方向のマイナスにスピードアップ。90°以上に傾いた時、ゲームオーバー関係。
          playing = false;
        // ゲームオーバーの条件。下記に記載。
          this.rSpeed = 30;
        // 回転スピード地面に接着している時。
          k.ArrowUp = 10;
          this.x -= speed * 18;
        // 回転スピードを早くする。
        }
        var angle = Math.atan2((p2 - 25) - this.y, (this.x + 5) - this.x);
        // 変数を宣言。プレイヤーの角度を変更する。
        // Math.atan2()関数、Math.atan2(y,x)に対して点(0,0)から点(x,y)までの半直線と、正のx軸の間の平面上での角度(ラジアン単位)を返す。
        // キャラクターのx,y座標をもとにアングルを設定している。
        if(grounded && playing) {
          // 地面にふれたら処理が行われる。
          this.rot = 0;
          this.rSpeed = this.rSpeed - (angle -this.rot);
        }
        this.rSpeed = this.rSpeed + (k.ArrowLeft - k.ArrowRight) * 1.2;
        // キーの回転スピード。
        this.rot = this.rot - this.rSpeed * 0.02;
        // プレイヤーの回転スピード。
        if(this.rot > Math.PI) this.rot = -Math.PI;
        if(this.rot < -Math.PI) this.rot = Math.PI;
        // 回転関係の設定？
        ctx.save();
        // 画面を保存する。再描状態を保存する。restore()とセット。
        ctx.translate(this.x,this.y);
        // ctx.translate画面を移動させる。画面の調整。
        ctx.rotate(this.rot);
        // キャラのx,y座標を元にキャンバスを回転させる。
        // save()内あるのでキャラの画像のみ回転する。今回は
        ctx.drawImage(this.img, -25, -25, 50, 50);
        // ctx.drawImage画像を描画するために使用する。
        // tx.drawImage(取込む画像, 横の位置, 高さの位置, プレイヤーの画像横幅, プレイヤーの画像縦幅)
        ctx.restore();
        // 画面を保存する。再描状態を保存する。save()とセット。
      }
    }
    var t = 0;
    // ループするために記載。アニメーションの起動。ループするたびにtの値が増加する。
    var speed = 0;
    // スピードの宣言。
    var playing = true;
    // playingを定義する。play出来るか出来ないかを設定。ゲームオーバ関係。
    // falsになると出来ないように
    var k = {ArrowUp: 0, ArrowDown: 0, ArrowLeft: 0, ArrowRight: 0};
    // 矢印キー用のキーの宣言。
    function loop() {
      if(speed > 0) {
        t = t + speed * 10;
        } else {
          speed = speed + k.ArrowUp ;
          t = t + speed * 10;
          // キーを押すことによって、スピードを変更することが出来る。画面の描写。
        }
      // ctx.fillStyle = "rgba(0,0,0,1)";
      // ctx.fillStyle = "red";
      // ctx.fillRect(0, 0, canvas.width, canvas.height);
      // 背景赤色。
      // バック画面。fillStyle塗り潰し。画面の描写。
      var img = new Image();
      img.src = "/images/haimen.jpg";
      // ⭐️画像読み込み終了してから描画
      img.onload = function(){
          ctx.drawImage(img, 0, 0,canvas.width,canvas.height);
      }
      ctx.fillStyle = "rgb(250, 180, 100)";
      // 山の色。山の描写。
      ctx.beginPath();
      // beginPath()、線を描画するために使用。山の斜面。山の描写。
      ctx.moveTo(0, canvas.height);
      // context.moveTo(x,y)新しいサブパスの開始点を座標指定する。
      // サブパスとは、パスを構成する線の一本のこと。
      // 今回はy=0は左上隅。c.heightは左下隅。
      // for loopにてどんどん次の点を決めていく。山の描写。
      for (var i = 0; i < canvas.width; i++) {
      // 山の斜面をどんどん右から左に移動させるため。細かい点を分割したもの連続表示。山の描写。
        ctx.lineTo(i, canvas.height - noise(t + i) * 0.4);
        // 山の高さを描写。ここ以外にも編集する必要がある。
        // lineTo線を引く関数。lineTo(始点, 終点)を表示させる。山の斜面。
        // c.height - を追加することによって山の高さを編集する。
        // 0.25倍することによって山の高さを編集する。
        // noise(t + i) tをたすことによって、画面が動いているようになる。
        // iは連続表示？消すと横線になる。山の点を保存表現？
      }
      ctx.lineTo(canvas.width, canvas.height);
      // ループが終わるとlineTo線を引く関数で、右端を指定。終点。山の描写。
      ctx.fill();
      // ctx.fillの間でlineTo山の線引きをループさせ塗りつぶす。山の斜面。
      player.draw();
      // プレイヤーの読み込み。プレイヤーの表示。
      requestAnimationFrame(loop);
    // ブラウザにアニメーションを行たいことを知らせ、指定した関数を呼び出して次の再描画の前にアニメーションを更新することを要求する。
    // 短い時間で画面を更新する。画面の描写。画面の繰り返し。
    }


    onkeydown = d => k[d.key] = 1;
    // onkeydownキーを押す時。キーを配列にして入れる？
    onkeyup = d => k[d.key] = 0;
    // onkeyupキーを離した時、キーを配列に入れる？押したキーの名前？
    // ⭐️押しているか押していないか判断する記述。
    loop();
    // ループの開始。画面の繰り返し。
  });
  </script>